---
title: Writing Samples
author: SP
date: '2017-09-27'
slug: writing-samples
categories:
  - writing
tags:
  - write
---

Spoiler warning up through Season 7 of Game of Thrones
In the event you've been living under a rock, Game of Thrones is an HBO TV series adapted from the incomplete "A Song of Ice and Fire" novels by George R.R Martin. It is written for TV by David Benioff and D.B Weiss and just finished its seventh season. Overall I thoroughly enjoyed it, but with my reservations. This season had the show flaunting it's very best, and simultaneously setting a new low point. I think this can be narrowed down to the way Game of Thrones uses combat, and how that can convey the story at large. 
Here's one example of the show at it's apex, the infamous "loot train attack" in episode 4, Spoils of War. For some brief background, this is the episode Daenerys uses one of her dragons, Drogon, to scorch the Lannister army commanded by Jaime Lannister. Spoils of War was a masterclass in its depiction of battle, and perfectly presented the moral ambiguity of the show, superbly characterized by its thrilling climax. Jaimie, with a newly minted sense of honor, grabs a spear and charges Daenerys, who most viewers have been rooting for since 'Thrones inception. It would be the ultimate victory for Jaime, and is very telling about the courage he possesses. But as soon as Drogon rears his terrifying head and summons his fire breath, I felt horrified just as I'm sure Jaimie felt. That's what makes combat so riveting in Game of Thrones and why I fell in love with the books and show in the first place, real combat is hell, no matter who you are. 
Now to contrast that, in season 7 episode 6, Beyond the Wall, that gray area disappears entirely. Here, Jon and seven others head beyond the wall to capture a living zombie and convince Queen Cersei to agree to a cease fire. Barring the absurdity and viability of this plan, and a thousand other issues I have with the episode, I'm just going to focus on one aspect. The unmentioned scouts. You may know them as "the guys wearing hoods". The issue is, viewers never see them unless they die, and they only serve to artificially create tension because no main character can be killed off. Part of what made Spoils of War great was the way foot soldiers were given an identity, and as a result we could empathize as they screamed for help. Sure there were two named deaths in this episode, but for the most part we saw hordes of zombies overrun people we never knew, and watched our heroes escape only through a combination of suspension of disbelief, and deus-ex machina.  The plot very clearly demands none of big names die here and because of that, the writers make silly choices to justify characters survival. The end result, while still visually stunning, was an awkward, rushed, mess. 
I'm not suggesting every scene be a tedious shot of talking and walking, but the violence in this show works so well because you really care about the parties involved. It's too easy now to abandon the shades of gray that make Game of Thrones amazing, and end up with conflict that simply rings hollow. 
